name: Build and Push Docker Image to Docker Hub

on:
  push:
    branches: [ main, master ]
    paths:
      - 'src/**'
      - 'models/**'
      - 'Dockerfile'
      - 'requirements.txt'
  workflow_dispatch:  # Allow manual trigger

env:
  DOCKER_USERNAME: 2024aa05871
  IMAGE_NAME: heart-disease-api

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=sha,prefix={{branch}}-
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64

      - name: Image digest
        run: echo ${{ steps.meta.outputs.digest }}

      - name: Update deployment status
        run: |
          echo "✅ Docker image built and pushed successfully!"
          echo "Image: ${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:latest"
          echo "Digest: ${{ steps.meta.outputs.digest }}"
